version: "2"

linters:
  disable:
    - unused
    - staticcheck
    - misspell
    - ineffassign
    - govet
    - errcheck
formatters:
  enable:
    - gofmt
  # settings:
  #   gofmt:
  #     simplify: true
  # exclusions:
  #   generated: lax
