name: Create releases
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    name: release
    if: github.ref == 'refs/heads/main' && github.repository == 'openai/openai-go'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}

    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    name: publish
    needs: release
    if: ${{ needs.release.outputs.releases_created == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false

      - name: Generate godocs
        run: |
          version="$(jq -r '. | to_entries[0] | .value' .release-please-manifest.json)"
          module="$(awk '$1 == "module" { print $2; exit }' go.mod)"
          curl --fail --show-error --silent -X POST "https://pkg.go.dev/fetch/${module}@v${version}"
